apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_NAME: 'homework-otus'
  APP_VERSION: '1.0.0'
  APP_PORT: '8000'
  APP_LOGLEVEL: 'debug'
  APP_TIMEOUT: '5'
  DB_HOST: {{ .Values.postgresql.fullnameOverride | quote }}
  DB_PORT: {{.Values.postgresql.global.postgresql.service.ports.postgresql | quote}}
  DB_NAME: {{.Values.postgresql.global.postgresql.auth.database | quote}}
  DB_USER: {{.Values.postgresql.global.postgresql.auth.username | quote}}
