apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "userservice.fullname" . }}
  labels:
    {{- include "userservice.labels" . }}
spec:
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
    selector:
      matchLabels:
        {{- include "userservice.selectorLabels" . | nindent 6 }}
    endpoints:
      - interval: 5s
        port: http
        path: '/metrics'
    jobName: {{ include "userservice.fullname" . }}