version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=homework
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/20221015205029_migration.up.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - home_net
  app:
    build: .
    container_name: otushw-stan
    image: ssv682/otus-homework3-repo:v0.1
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - home_net

networks:
  home_net:
    driver: bridge

volumes:
  db:
