version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=homework
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
#    volumes:
#      - db:/var/lib/postgresql/data
#      - ./migrations/db/20221015205029_migration.up.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - home_net

  userService:
    build:
      dockerfile: ./user-service/Dockerfile
      context: ./
    container_name: user-service
    image: ssv682/user-service:v0.3
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - home_net
    links:
      - authService

  authService:
    build: ./auth-service
    container_name: auth-service
    image: ssv682/auth-service:v0.1
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - home_net

  orderService:
    build: ./order-service
    container_name: order-service
    image: ssv682/order-service:v0.1
    ports:
      - "8002:8000"
    depends_on:
      - db
      - redis
    networks:
      - home_net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - home_net
    depends_on:
      - userService

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - home_net
    depends_on:
      - userService

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - home_net
#    command: redis-server  /usr/local/etc/redis/redis.conf --requirepass redis-pass
#    volumes:
#      - ./dev/redis/redis.conf:/usr/local/etc/redis/redis.conf


networks:
  home_net:
    driver: bridge

volumes:
  db:
