{
 "title": "New dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory usage (gb)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg(nginx_ingress_controller_nginx_process_resident_memory_bytes/(1024*1024*1024)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of 500 status code (service)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(echo_http_error_rate_by_user_service[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of 499 and 500 status code (ingress)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"499|500|502\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histograms (service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(echo_http_response_time_seconds_bucket{path!='/metrics'}[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(echo_http_response_time_seconds_bucket{path!='/metrics'}[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(echo_http_response_time_seconds_bucket{path!='/metrics'}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histograms (ingress)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS (service)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(echo_http_http_request_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS (ingress)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "postgres",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"postgres-exporter-prometheus-postgres-exporter\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Average latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(echo_http_response_time_seconds_sum[1m])) / sum(rate(echo_http_response_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}