apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
data:
  APP_NAME: 'homework-otus'
  APP_VERSION: '1.0.0'
  APP_PORT: '8000'
  APP_LOGLEVEL: 'debug'
  APP_TIMEOUT: '5'
  POSTGRES_HOST: {{ .Values.postgresql.fullnameOverride | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.global.postgresql.service.ports.postgresql | quote }}
  POSTGRES_NAME: {{ .Values.postgresql.global.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.global.postgresql.auth.username | quote }}
  AUTH_HOST: {{ .Values.authservice.host | quote }}
  AUTH_PORT: {{ .Values.authservice.port | quote }}
  AUTH_ENDPOINT: {{ .Values.authservice.endpoint | quote }}
  REDIS_HOST: {{ .Values.redis.fullnameOverride | quote }}
  REDIS_PORT: {{ .Values.redis.cluster.externalAccess.service.port | quote }}

