app:
  name: 'homework-otus'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'homework-otus'

conn:
  host: 'db'
  port: '5432'
  dbname: 'homework'
  user: 'postgres'
  password: 'password'

timeout:
  duration : '5'

