name: Lint Go Code

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.19.1'
      - name: lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.
          sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          
          golangci-lint run